version: '3'

services:
  jax:
    build:
      context: .
      dockerfile: ./docker/jax/Dockerfile
      args:
        - UID=${USERID}
        - USERNAME=dockeruser
        - TENSORFLOW_VERSION=2.8.0
        - JAXLIB_VERSION=0.3.5
        - JAX_CUDA_VERSION=11
        - JAX_CUDNN_VERSION=805
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes:
      - .:/usr/src
      - //mnt/D/Data/animefacedataset/images:/usr/src/data
    tty: true
    shm_size: '2gb'
    working_dir: /usr/src
